# Generated by Django 5.2.5 on 2025-08-26 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('idTarefa', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('prioridade', models.CharField(choices=[('Alta', 'Alta'), ('Média', 'Média'), ('Baixa', 'Baixa')], max_length=6)),
                ('setor', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=7)),
                ('dataCriacao', models.DateTimeField()),
                ('status', models.CharField(choices=[('Progredindo', 'Progredindo'), ('Fazer', 'Fazer'), ('Concluído', 'Concluído')], max_length=11)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.usuario')),
            ],
        ),
    ]
