# Generated by Django 5.2.5 on 2025-08-25 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTarefa', models.IntegerField()),
                ('descricao', models.CharField(max_length=255)),
                ('setor', models.BooleanField(verbose_name={'Ativo': 'Ativo', 'Inativo': 'Inativo'})),
                ('dataCriacao', models.DateTimeField()),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.usuario')),
            ],
        ),
    ]
