# Generated by Django 5.2.6 on 2025-10-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criartarefa',
            name='idTarefa',
        ),
        migrations.AddField(
            model_name='criartarefa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
