# Generated by Django 5.2.6 on 2025-10-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_remove_criartarefa_idtarefa_criartarefa_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criartarefa',
            name='id',
        ),
        migrations.AddField(
            model_name='criartarefa',
            name='idTarefa',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
