# Generated by Django 5.2.5 on 2025-08-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='setor',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=7),
        ),
    ]
